{ pkgs, inputs, ... }:
{
  systemPackages = with pkgs; [
    wget
    git
    swaybg
    playerctl
    wl-clipboard
    libmtp
    mtpfs
    kdePackages.kio-extras
    android-tools
    tree
    appimage-run
    ffmpeg
    inputs.self.packages.${pkgs.system}.spotiflac
    unrar
    thunar
  ];
  userPackages = with pkgs; [
    localsend
    inputs.zen-browser.packages."${pkgs.stdenv.hostPlatform.system}".default
    inputs.self.packages.${pkgs.system}.ab-download-manager
    inputs.self.packages.${pkgs.system}.prismlauncher-cracked
    btop
    mpc
    kdePackages.dolphin
    grim
    slurp
    wlsunset
    hyprsunset
    docker-compose
    lazydocker
    android-file-transfer
    libreoffice-fresh
    qbittorrent
    telegram-desktop
    vlc
    opus-tools
    stremio-linux-shell
    heroic
  ];
  nixLdLibraries = with pkgs; [
    stdenv.cc.cc
    zlib
    fuse3
    icu
    nss
    openssl
    curl
    expat
  ];
}
